// GENERATED by /tmp/mapgen/gen.mjs (d3-geo Natural Earth projection of Natural Earth 110m countries).
// Pins are city-level unless precision is "region" (the source names only a state or country).
export const MAP_W = 1000;
export const MAP_H = 500;
export type Origin = { slug: string; label: string; precision: "city" | "region"; x: number; y: number };
export const ORIGINS: Origin[] = [
 {
  "slug": "mk-gee",
  "label": "Linwood, NJ",
  "precision": "city",
  "x": 308.4,
  "y": 160.2
 },
 {
  "slug": "nia-archives",
  "label": "Bradford & Leeds, England",
  "precision": "city",
  "x": 496.3,
  "y": 114.7
 },
 {
  "slug": "paris-texas",
  "label": "Los Angeles, CA",
  "precision": "city",
  "x": 189.8,
  "y": 177.2
 },
 {
  "slug": "riz-la-vie",
  "label": "New Jersey",
  "precision": "region",
  "x": 309.2,
  "y": 157.7
 },
 {
  "slug": "oliver-malcolm",
  "label": "Sweden / England",
  "precision": "region",
  "x": 496.2,
  "y": 118.1
 },
 {
  "slug": "contradash",
  "label": "Orange County, CA",
  "precision": "city",
  "x": 190.5,
  "y": 178.3
 },
 {
  "slug": "ninajirachi",
  "label": "Kincumber, NSW",
  "precision": "city",
  "x": 898,
  "y": 395
 },
 {
  "slug": "fakemink",
  "label": "Essex, England",
  "precision": "region",
  "x": 501.2,
  "y": 120.9
 },
 {
  "slug": "devon-again",
  "label": "Near Denver, CO",
  "precision": "city",
  "x": 230.7,
  "y": 158.9
 },
 {
  "slug": "dove-ellis",
  "label": "Galway, Ireland",
  "precision": "city",
  "x": 478.4,
  "y": 116.3
 },
 {
  "slug": "absolutely",
  "label": "England",
  "precision": "region",
  "x": 496.2,
  "y": 118.1
 },
 {
  "slug": "jean-dawson",
  "label": "San Diego / Tijuana",
  "precision": "city",
  "x": 191.2,
  "y": 181.5
 },
 {
  "slug": "nettspend",
  "label": "Richmond, VA",
  "precision": "city",
  "x": 299.5,
  "y": 166
 },
 {
  "slug": "whatmore",
  "label": "New York City",
  "precision": "city",
  "x": 311,
  "y": 155.8
 },
 {
  "slug": "bleood",
  "label": "Florida",
  "precision": "region",
  "x": 280.7,
  "y": 196.8
 },
 {
  "slug": "sailorr",
  "label": "Jacksonville, FL",
  "precision": "city",
  "x": 283.1,
  "y": 189.3
 },
 {
  "slug": "jahson-paynter",
  "label": "Mississauga, ON",
  "precision": "city",
  "x": 299.3,
  "y": 146.6
 },
 {
  "slug": "jessy-lanza",
  "label": "Hamilton, ON",
  "precision": "city",
  "x": 298.4,
  "y": 147.6
 },
 {
  "slug": "sarah-kinsley",
  "label": "New York City",
  "precision": "city",
  "x": 311,
  "y": 155.8
 },
 {
  "slug": "quiet-light",
  "label": "Austin, TX",
  "precision": "city",
  "x": 240.3,
  "y": 189.5
 },
 {
  "slug": "natanya",
  "label": "North West London",
  "precision": "city",
  "x": 499.4,
  "y": 121.6
 },
 {
  "slug": "sassy-009",
  "label": "Oslo, Norway",
  "precision": "city",
  "x": 524.5,
  "y": 96.4
 },
 {
  "slug": "the-deep",
  "label": "South Korea",
  "precision": "region",
  "x": 832.3,
  "y": 169.3
 },
 {
  "slug": "fcukers",
  "label": "New York City",
  "precision": "city",
  "x": 311,
  "y": 155.8
 },
 {
  "slug": "sofia-isella",
  "label": "Los Angeles, CA",
  "precision": "city",
  "x": 189.8,
  "y": 177.2
 },
 {
  "slug": "cece-natalie",
  "label": "Connecticut",
  "precision": "region",
  "x": 315,
  "y": 152.9
 },
 {
  "slug": "bleech-9-3",
  "label": "Dublin, Ireland",
  "precision": "city",
  "x": 485.1,
  "y": 116.1
 },
 {
  "slug": "chalk",
  "label": "Belfast, N. Ireland",
  "precision": "city",
  "x": 486,
  "y": 112.3
 },
 {
  "slug": "tiffany-day",
  "label": "Wichita, KS",
  "precision": "city",
  "x": 248.1,
  "y": 165.5
 },
 {
  "slug": "slauson-malone-1",
  "label": "Los Angeles, CA",
  "precision": "city",
  "x": 189.8,
  "y": 177.2
 },
 {
  "slug": "kllo",
  "label": "Melbourne, Australia",
  "precision": "city",
  "x": 874.9,
  "y": 409
 },
 {
  "slug": "gazelle-twin",
  "label": "England",
  "precision": "region",
  "x": 496.2,
  "y": 118.1
 },
 {
  "slug": "jessica-93",
  "label": "Paris region, France",
  "precision": "region",
  "x": 506,
  "y": 129.8
 },
 {
  "slug": "sudan-archives",
  "label": "Cincinnati, OH",
  "precision": "city",
  "x": 282.6,
  "y": 161
 },
 {
  "slug": "the-sophs",
  "label": "Los Angeles, CA",
  "precision": "city",
  "x": 189.8,
  "y": 177.2
 },
 {
  "slug": "eaves-wilder",
  "label": "North London",
  "precision": "city",
  "x": 499.7,
  "y": 121.5
 },
 {
  "slug": "alessi-rose",
  "label": "Derby, England",
  "precision": "city",
  "x": 496.5,
  "y": 117.4
 },
 {
  "slug": "shes-green",
  "label": "Minneapolis, MN",
  "precision": "city",
  "x": 266.6,
  "y": 142.2
 },
 {
  "slug": "jade-lemac",
  "label": "Vancouver, BC",
  "precision": "city",
  "x": 199.1,
  "y": 128.6
 },
 {
  "slug": "lael-neale",
  "label": "Rural Virginia",
  "precision": "region",
  "x": 295.7,
  "y": 165.1
 },
 {
  "slug": "hand-habits",
  "label": "Amsterdam, NY",
  "precision": "city",
  "x": 312.4,
  "y": 148.7
 },
 {
  "slug": "lime-garden",
  "label": "Brighton, England",
  "precision": "city",
  "x": 499.7,
  "y": 123.8
 },
 {
  "slug": "model-actriz",
  "label": "Boston, MA",
  "precision": "city",
  "x": 319.9,
  "y": 150.5
 },
 {
  "slug": "gia-margaret",
  "label": "Chicago, IL",
  "precision": "city",
  "x": 277.4,
  "y": 152
 },
 {
  "slug": "english-teacher",
  "label": "Leeds, England",
  "precision": "city",
  "x": 496.3,
  "y": 114.7
 },
 {
  "slug": "jenny-hval",
  "label": "Norway",
  "precision": "region",
  "x": 520.3,
  "y": 93.2
 },
 {
  "slug": "sprints",
  "label": "Dublin, Ireland",
  "precision": "city",
  "x": 485.1,
  "y": 116.1
 },
 {
  "slug": "indigo-de-souza",
  "label": "Asheville, NC",
  "precision": "city",
  "x": 284.6,
  "y": 172.2
 },
 {
  "slug": "sam-amidon",
  "label": "Brattleboro, VT",
  "precision": "city",
  "x": 316.5,
  "y": 148.9
 }
];
export const VIEWS: Record<string, [number, number, number, number]> = {"World":[0,0,1000,500],"North America":[194,111,139,99],"UK & Ireland":[474,98,32,30],"Europe":[473,90,68,65],"Australia":[872,384,27,32]};
